services:
  app:
    build:
      context: .
    container_name: adserver-app
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - adserver-network
  
  caddy:
    image: caddy
    container_name: adserver-caddy
    depends_on:
      - app
    ports:
      - 8080:8080
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - adserver-network

  postgres:
    image: postgres:bookworm
    restart: always
    container_name: adserver-db
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [CMD-SHELL, "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./scripts/docker:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    networks:
      - adserver-network

volumes:
  pg-data:
  caddy-config:
  caddy-data:

networks:
  adserver-network:
