name: CI/CD to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Verify Depedencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run Tests
        run: go test -race ./...

  deploy:
          needs: test # Ensure CI job passes before deploying
          runs-on: ubuntu-latest
          steps:
            - name: Trigger Render Deploy
              run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}