name: Run Render CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Verify Depedencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run Tests
        run: go test -race ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test 
    if: github.ref == 'refs/heads/main'
    env:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
    steps:
      - name: Trigger Render Deploy
        run: curl "$RENDER_DEPLOY_HOOK_URL"